### ISSUE TITLE
[Bug]: Invite process fails when DMs turned off

### ISSUE THREAD

**Issue by jimthedev** [Developer-DAO/DAO-pairbot#24]
### What happened?

A person with DMs turned off in their discord settings cannot go through the accept invite process.

The person will be unable to see pending invites or accept invites for pairing since the process requires DMs to work. It is common for people in many NFT servers to turn off DMs due to the vast number of spam DMs. An error will be thrown when the bot attempts to send a DM. In this case one option would be to have a channel with pairing requests where people are tagged via <@discord_id_here> so that they get a red indicator by the channel and can choose to see why they have been tagged (to have a pairing session).

I am happy to work on this and will add it to the Project board if you want to give me perms @mbuxmann.

### How to reproduce the bug?

Go to User Settings in Discord. 
Make sure the following setting is toggle off as shown here:
<img width="705" alt="Screen Shot 2021-12-03 at 7 58 59 PM" src="https://user-images.githubusercontent.com/108938/144692863-1f8da3b7-aa8f-4991-9549-655a80d9bb08.png">
Have someone send you an invite for pairing. You will never get the DM.

### Additional information

My proposed solution above is, send a fallback message to a pairing channel where someone will be tagged with a message that gives them the command to execute if they accept the pairing invitation, something like /accept-invitation invitation {id_here}

**Comment by jimthedev** [comment]
Screenshot of what the proposed solution looks like in a log channel.
<img width="1181" alt="Screen Shot 2021-12-04 at 12 26 02 AM" src="https://user-images.githubusercontent.com/108938/144700131-0ed9372f-4c53-4e8c-8a81-d09a316764f4.png">
n

**Comment by mbuxmann** [comment]
HI @jimthedev,

This is much needed and I really appreciate it, thank you very much! I've given you write permissions so you should be able to add/edit things on the project board now.

**Comment by jimthedev** [comment]
Great, thanks @mbuxmann!
